# Generated by Django 5.0.6 on 2024-07-01 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
