# Generated by Django 5.0.6 on 2024-07-01 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_answer_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='downvotes',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='upvotes',
        ),
    ]
